Added ignore case to map based parser and added tests
PoweredByApartium/cocoa-beans pull request #134
Opened 2024-07-28 18:27 UTC by ikfir

Closes #131

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation)
- [ ] 🐞 Bug fix (fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)

### 📚 Description
Added ignore case to constructor with ignore case

### 🧪 How Has This Been Tested?
Unit testing

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2024-07-28 20:25 UTC, liorsl requested changes

2024-07-28 20:25 UTC, liorsl commented on commands/src/main/java/net/apartium/cocoabeans/commands/parsers/MapBasedParser.java
> +                s = s.toLowerCase();
._.

2024-07-29 05:29 UTC, ikfir commented on commands/src/main/java/net/apartium/cocoabeans/commands/parsers/MapBasedParser.java
> +                s = s.toLowerCase();
._.

2024-08-02 19:31 UTC, liorsl approved these changes

2024-08-02 19:32 UTC, merged