[commands] Compound Parser
PoweredByApartium/cocoa-beans pull request #216
Opened 2024-11-29 21:43 UTC by ikfir

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation)
- [x] 🐞 Bug fix (fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (adds functionality)

### 📚 Description
Compound parser is a simple way to create custom parsers that are composed of other parsers
For example if we want to create a simple location parser it will be the following:
```java
@WithParser(DoubleParser.class)
@WithParser(FloatParser.class)
@WithParser(WorldParser.class)
public class LocationParser extends CompoundParser<Location> {
    
    public static final String DEFAULT_KEYWORD = "location";
    
    public LocationParser(int priority, String keyword) {
        super(
          keyword,
          Location.class,
          priority,
          new SimpleArgumentMapper(),
          new SimpleCommandLexer()
        );
    }

    public LocationParser(int priority) {
        this(priority, DEFAULT_KEYWORD);
    }

    @ParserVariant("<world> <double> <double> <double>")
    public Location parseWorldWithXyz(World world, double x, double y, double z) {
        return new Location(world, x, y, z);
    }

    @ParserVariant("<world> <double> <double> <double> <float> <float>")
    public Location parseWorldWithXyzYawPitch(World world, double x, double y, double z, float yaw, float pitch) {
        return new Location(world, x, y, z, yaw, pitch);
    }
    

    @SenderLimit(SenderType.PLAYER)
    @ParserVariant("<double> <double> <double>")
    public Location parseWithXyz(Player sender, double x, double y, double z) {
        return new Location(
                sender.getWorld(),
                x,
                y,
                z
        );
    }

    @SenderLimit(SenderType.PLAYER)
    @ParserVariant("<double> <double> <double> <float> <float>")
    public Location parseWithXyzYawPitch(Player sender, double x, double y, double z, float yaw, float pitch) {
        return new Location(
                sender.getWorld(),
                x,
                y,
                z,
                yaw,
                pitch
        );
    }
}
```

### 🧪 How Has This Been Tested?
Unit testing

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2024-11-29 22:50 UTC, ikfir commented on commands/src/test/java/net/apartium/cocoabeans/commands/parsers/compound/PositionParser.java
> +    }
just a test doesn't really need it

2024-11-29 22:50 UTC, ikfir commented on commands/spigot-platform/src/test/java/net/apartium/cocoabeans/commands/spigot/parsers/MeowParser.java
> +    }
test doesn't mattar

2024-11-29 23:10 UTC, ikfir commented on commands/src/test/java/net/apartium/cocoabeans/commands/GeneralCommandTest.java
> +    }
We may need to open issue about stress test

2024-12-05 15:25 UTC, liorsl requested changes

2024-12-05 15:25 UTC, liorsl commented on Writerside/topics/Examples.md
> +* [`Compound parser`]()
need link here

2024-12-05 15:25 UTC, liorsl commented on commands/spigot-platform/src/main/java/net/apartium/cocoabeans/commands/spigot/requirements/factory/PermissionFactory.java
> +                return RequirementResult.meet();
shouldn't it fail? even if its inverted, its not a valid sender

2024-12-08 14:54 UTC, liorsl approved these changes

2024-12-08 14:54 UTC, merged