Release ci
PoweredByApartium/cocoa-beans pull request #98
Opened 2024-06-25 16:05 UTC by IdanKoblik

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation)
- [x] 🐞 Bug fix (fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)

### 📚 Description

### 🧪 How Has This Been Tested?
![img](https://i.imgur.com/PReeWZc_d.webp?maxwidth=760&fidelity=grand)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2024-06-25 16:31 UTC, liorsl requested changes

2024-06-25 16:31 UTC, liorsl commented on .github/workflows/callable.test.yml
> +                commands
forgot something

2024-06-25 16:31 UTC, liorsl commented on .github/workflows/release.yml
> +  pull-requests: write
why is this needed?

2024-07-05 17:41 UTC, liorsl requested changes

2024-07-05 17:41 UTC, liorsl commented on .github/workflows/callable.test.yml
> +    pages: write
why is this needed?

2024-07-05 17:41 UTC, liorsl commented on .github/workflows/callable.test.yml
> +    packages: write
why is this needed?

2024-07-05 17:41 UTC, liorsl commented on .github/workflows/callable.test.yml
> +    id-token: write
why is this needed?

2024-07-05 17:41 UTC, liorsl commented on .github/workflows/callable.test.yml
> +                commands
you didnt fix this

2024-07-05 17:41 UTC, liorsl commented on .github/workflows/callable.writerside.yml
> +  packages: write
why is this needed?

2024-07-05 17:41 UTC, liorsl commented on .github/workflows/callable.writerside.yml
> +  id-token: write
why is this needed?

2024-07-05 17:41 UTC, liorsl commented on .github/workflows/main.yml
> +  pull-requests: write
why is this needed?

2024-07-05 17:41 UTC, liorsl commented on .github/workflows/main.yml
> +          new_version: snapshot
Variables???

2024-07-05 17:41 UTC, liorsl commented on .github/workflows/release.yml
> +          input_file="Writerside/writerside.cfg"
looks familiar

2024-07-06 18:51 UTC, ikfir commented on .github/workflows/callable.test.yml
> +    pages: write
why?

2024-07-06 19:00 UTC, ikfir commented on build-scripts/prepare-web-output.sh
> +mkdir $docs
add if to make sure `$docs` is not empty / null

2024-07-06 20:12 UTC, liorsl commented on Writerside/topics/Home.md
> +* [Commands javadocs](https://cocoa-beans.apartium.net/%version%/commands/)
Forgot something????

2024-07-06 21:14 UTC, liorsl commented on .github/workflows/pull_request.yml
> -      - main
this should still be here though

2024-07-06 22:07 UTC, liorsl approved these changes

2024-07-06 22:07 UTC, merged